# Generated by Django 5.2.6 on 2025-09-30 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('niveau_requis', models.CharField(choices=[('BAC', 'Bac'), ('BAC+2', 'Bac+2'), ('BAC+3', 'Licence/Bac+3'), ('MASTER', 'Master')], max_length=10)),
                ('description', models.TextField()),
                ('frais_inscription', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_limite', models.DateField()),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Concours',
            },
        ),
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenoms', models.CharField(max_length=200)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('nationalite', models.CharField(default='Ivoirienne', max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.TextField()),
                ('niveau_etudes', models.CharField(max_length=100)),
                ('etablissement_origine', models.CharField(max_length=200)),
                ('annee_obtention', models.IntegerField()),
                ('numero_inscription', models.CharField(blank=True, max_length=20, unique=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('valide', models.BooleanField(default=False)),
                ('concours_souhaite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inscriptions.concours')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('EXTRAIT', 'Extrait de naissance'), ('CERTIFICAT', 'Certificat de scolarité'), ('DIPLOME', 'Diplôme'), ('LETTRE', 'Lettre de motivation'), ('PHOTO', "Photo d'identité"), ('AUTRE', 'Autre document')], max_length=20)),
                ('fichier', models.FileField(upload_to='documents/%Y/%m/')),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='inscriptions.candidat')),
            ],
            options={
                'unique_together': {('candidat', 'type_document')},
            },
        ),
    ]
